### ISSUE TITLE
[Feature Request] Ability to amend commit?

### ISSUE THREAD

**Issue by storm1er** [bendera/vscode-commit-message-editor#1]
Hi,

Everything is in title, is it possible to add a "amend commit" into the editor.
So when clicking save, it will complete the field (as now) but also do a `git reset HEAD^` so file from previous commits appears =)

**Comment by bendera** [comment]
Hi,

Thank you for the idea, I like it. I've investigated a bit, and I found that the built-in "Undo Last Commit" command does exactly this. This command is accessible from the "More options..." menu or the command palette, and easily callable from the extension API. So, I will add it to the next release.
