### ISSUE TITLE
[bug] Error: Could not register service worker: InvalidStateError

### ISSUE THREAD

**Issue by mdarkzar** [bendera/vscode-commit-message-editor#107]
Hello!

After updating vcode to version 1.82
I started getting errors when trying to use the plugin: 

`Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..`

**Comment by bendera** [comment]
Hi,

Thanks for the bug report. I think this is the same issue, I'll wait to see what the result will be.
https://github.com/microsoft/vscode/issues/192965

**Comment by bendera** [comment]
Fixed in the new VSCode.
