### ISSUE TITLE
[bug] Sometimes the `Type of change` goes away in commit message

### ISSUE THREAD

**Issue by vinicioslc** [bendera/vscode-commit-message-editor#12]
Hi i founded a bug when change one file in another window, go back to plugin page and hit save button, the type of change in commit goes away, follow the gif. 

![commit_message_editor_bug](https://user-images.githubusercontent.com/10997022/95124540-f7f4c800-0729-11eb-85e2-2582577bce3e.gif)

I want fix this bug to participate from hacktober fest if you like this contribution please add the topic hacktoberfest in repository page.

Im made this because have some repos without activity, and forgotten, i expect there is not the case.

**Comment by bendera** [comment]
Hi,

Thank you for your help, I'm looking forward to your PR. :)

**Comment by vinicioslc** [comment]
I have made a pull request that fix this issue and made a little refactor in how values are loaded from the form #13
