### ISSUE TITLE
[feat] Multiline for tokens of enum 

### ISSUE THREAD

**Issue by frederikdekegel** [bendera/vscode-commit-message-editor#14]
First of all, let me says thanks for this great extension. Finally, a full customizable way to enter a customized conventional commit message tailored for my company.

There are a few things however, where an improvement would be greatly appreciated. One of those improvements is the ability to select multiple values for the enum / dropdown token type. Those values are separated using a configurable separator.

Reason: in our implementation of conventional commits, we have fixed values for the scope part. The developers enter 1 or more scopes depending on the nature of the changes they performed. Those scopes are later on used to for example generate changelogs.

**Comment by bendera** [comment]
I'm glad you like my extension. :)

It's a bit more complicated than the other one but can be solved.

**Comment by bendera** [comment]
Check the modified readme:
https://github.com/bendera/vscode-commit-message-editor#customizing-the-commit-message-form

**Comment by frederikdekegel** [comment]
Thank you 😊😊😊
