### ISSUE TITLE
[feat] Hide textarea tab through configuration

### ISSUE THREAD

**Issue by frederikdekegel** [bendera/vscode-commit-message-editor#15]
First of all, let me says thanks for this great extension. Finally, a full customizable way to enter a customized conventional commit message tailored for my company.

There are a few things however, where an improvement would be highly appreciated.  One of those improvements is the ability to completely hide textarea tab. 

Reason: When our developers fill out the textarea tab, they make more than one mistake against the conventional commit format, which we impose, even when the template is loaded. It is only when they perform the commit in Git, commitlint jumps in and throws an error. It is more efficient / productive, if they fill out the form tab.

**Comment by bendera** [comment]
I like the idea and especially easy to implement.

**Comment by bendera** [comment]
Done.
