### ISSUE TITLE
Add `chore` `revert` label

### ISSUE THREAD

**Issue by Airkro** [bendera/vscode-commit-message-editor#16]
For `@commitlint/config-conventional` compatibillity.

**Comment by bendera** [comment]
Hi,

The default config follows the Angular Framework's conventions for the time being. However it's just an example, you can customize it:
https://github.com/bendera/vscode-commit-message-editor#customizing-the-commit-message-form

**Comment by Airkro** [comment]
Thanks, I know it can be customized, but I try to convince you to make it default.

Reason:

- Angular's conventions have `revert` type, but this extension didn't have it.
- [conventional commits](https://conventionalcommits.org/) is more and more popular day by day.
- `conventional commits` includes all type from angular's conventions, only add one more `chore` type. It's a seamless change.
- **The most important thing is:** it's not easy to share vscode settings in a team, even today.

**Comment by bendera** [comment]
Okay, you've convinced me. :)

**Comment by bendera** [comment]
Done.
