### ISSUE TITLE
Create vsix extension in release

### ISSUE THREAD

**Issue by storm1er** [bendera/vscode-commit-message-editor#17]
To make your extension work in code-server <3 

See https://github.com/cdr/code-server/issues/2239

**Comment by storm1er** [comment]
See for how to https://code.visualstudio.com/api/working-with-extensions/publishing-extension#packaging-extensions

**Comment by bendera** [comment]
Hi,

I'm bit confused. What should I do exactly? Should I attach the compiled VSIX file to the (github) release? Is it necessary? I picked an extension randomly from the closed tickets, and there are no vsix files in the releases.

https://github.com/42Crunch/vscode-openapi/releases

**Comment by storm1er** [comment]
> _Should I attach the compiled VSIX file to the (github) release?_

Yes

> _Is it necessary?_

No, it just make their work easier (if I understood well)

----

It also allows code-server users to download and install the extension before it is released in code-server marketplace =)

**Comment by bendera** [comment]
Okay, I've figured out how to attach the binary to the release. :)
https://github.com/bendera/vscode-commit-message-editor/releases/tag/v0.14.3
