### ISSUE TITLE
Save Button fails to populate commit message box

### ISSUE THREAD

**Issue by Subterrane** [bendera/vscode-commit-message-editor#18]
I think the update of VSCode broke your extension.

VSCode Version: 1.51.0

Filling in the form and pressing "Save" doesn't fill in the commit message.

**Comment by bendera** [comment]
Again... I'm looking for a solution but I have no idea. :/

**Comment by miguelcarrascoq** [comment]
yes. Version: 1.51.0 has the problem. In the last VS Code works well

**Comment by bendera** [comment]
Phew. The new version is in the marketplace. I didn't believe it I would fix it.
