### ISSUE TITLE
[feat] Add support for gitmojis

### ISSUE THREAD

**Issue by mrvkino** [bendera/vscode-commit-message-editor#19]
Hi,

I wanted to know if the support for gitmoji is possible in the template. Listing all the options with enum is not realistic.

thanks

**Comment by bendera** [comment]
Hi,

Could you show me some sample commit messages? I would like to know how you want to use it.

**Comment by mrvkino** [comment]
I am using the gitmoji like this.
```
✨ feat: This is a new feature

This feature requires a description

Closes #...
```

Also the option to use string `:sparkles:` instead of the emoji ✨can be useful for people not using GitHub.

But with the custom template that can be place wherever the user want and can be optional like the scope.

Here is the [Gitmoji GitHub project](https://github.com/carloscuesta/gitmoji).

Conventional comment decided to be agnostic in their inclusion and let the user/implementer decide, [but was not against it](https://github.com/conventional-commits/conventionalcommits.org/issues/41).

**Comment by bendera** [comment]
It seems enum. I don't have a better idea either. Would a combo box or an autocomplete widget be acceptable to you?

**Comment by mrvkino** [comment]
An autocomplete widget could be used in both the "edit as text" and "edit as form". The best would be  to allow the user to search for the meaning and get the correct Gitmoji (see: https://gitmoji.dev).

ex: if the user type "refactor" the widget would put :recycle:. Or, if the user type "remove" it would get an autocomplete list for:
```
remove _code_or_files
remove_a_dependency
remove_logs
```

The project already has the association: (https://github.com/carloscuesta/gitmoji/blob/163b50ca55d10d3c4036a340396af126b3ed7be7/src/data/gitmojis.json)

**Comment by bendera** [comment]
Hi,

From now you can add the `combobox` option to the enum tokens, which means the select widget will be filterable. I've created a sample config too:
https://github.com/bendera/vscode-commit-message-editor/blob/master/example-configs/gitmojis.json
You can customize this file with this script: 
https://github.com/bendera/vscode-commit-message-editor/blob/master/scripts/gitmoji-config.js
