### ISSUE TITLE
Inconsistent behavior when Edit as a form

### ISSUE THREAD

**Issue by RAYDENFilipp** [bendera/vscode-commit-message-editor#2]
- Sometimes, when you pick a type of change in the form, an option may not be pickable and thus won't appear in it.
- Sometimes, when you chose a type of change, it will appear as --- in the commit message form.

**Comment by bendera** [comment]
Hi,

Thank you for your bug report. This is an error in the select component:

**Comment by bendera** [comment]
Hi,

Thank you for your bug report. This is an error in the select component:
https://github.com/bendera/vscode-webview-elements/blob/master/src/VscodeSelect.ts
I tried to fix earlier, but I couldn't. I have no idea for this problem at this time.

(Btw. an offtopic fun fact: we work at the same company. :))

**Comment by RAYDENFilipp** [comment]
> (Btw. an offtopic fun fact: we work at the same company. :))
Wow! Great to meet a fellow!

**Comment by bendera** [comment]
FIxed. (I hope so.)
