### ISSUE TITLE
Edit as form: make the body field higher + resizable

### ISSUE THREAD

**Issue by ngirard** [bendera/vscode-commit-message-editor#20]
Hi, and happy new year,

in "Edit as form", it would be much more convenient if the field for "body" was made higher and resizable.

Cheers, and thanks for your work !

**Comment by bendera** [comment]
Hi,

The `lines` and `maxLines` config options have added to the token config.

**Comment by ngirard** [comment]
Great, thanks ! This deserves a release on its own IMHO.

**Comment by bendera** [comment]
It's already done. ;)
