### ISSUE TITLE
The "open the commit message editor" icon dosen't show in dark theme.

### ISSUE THREAD

**Issue by JJLau626** [bendera/vscode-commit-message-editor#21]
Such as this pic, that icon dosen't show on my vscode when I using dark theme.
![微信截图_20210125093856](https://user-images.githubusercontent.com/26458821/105651323-82d41b00-5ef1-11eb-94a9-14705a592691.png)

**Comment by bendera** [comment]
Which theme do you use? I couldn't reproduce in the default dark theme.

**Comment by JJLau626** [comment]
> Which theme do you use? I couldn't reproduce in the default dark theme.

I am using Palenight Theme.

![image](https://user-images.githubusercontent.com/26458821/105726272-d9c70800-5f64-11eb-9f35-417db4bf479d.png)

**Comment by bendera** [comment]
I still couldn't reproduce. Which is the version of your VSCode? It is older than 1.50? I use a feature that was introduced in the 1.50:
https://code.visualstudio.com/updates/v1_52#_support-for-codicons-for-view-containers-views

**Comment by JJLau626** [comment]
> I still couldn't reproduce. Which is the version of your VSCode? It is older than 1.50? I use a feature that was introduced in the 1.50:
> https://code.visualstudio.com/updates/v1_52#_support-for-codicons-for-view-containers-views

Yes! you are right, my VSCode version was older than 1.50. After I update my VSCode,this issue was gone.Thanks for your help.
