### ISSUE TITLE
Source control windows goes blank

### ISSUE THREAD

**Issue by CasellesInventions** [bendera/vscode-commit-message-editor#26]
Hey! I have been using your extension for some months without any problem. For the last days, every time I do amend with the extension and save, then I click on the commit button on source control window and the source control window/tab gets corrupted. The text box "Message( Ctrl+Enter to commit ..." and the tab Changes dissapear forever. I can see Branches or Stashes (I think these ones come with GitLens, not plain VSCode).

This error persists for the repo I try to do the commit, but not for the other repos. I delete the repo and I clone one more time and the error persists. I reproduced for other repos and the same. If I clone the repo in a different folder after the error, it works one more time. Also, deleting ~/.config/Code (Ubuntu) to reset all VSCode parameters fix it too.

My VSCode version is 1.53.0 on Ubuntu 18 Linux x64

Thank you for the extension!

**Comment by bendera** [comment]
Hi,

I've experienced this issue but I thought I had tangled the IDE configuration somehow. :O I'm going to investigate it at the weekend. Until I fix it use the previous major version which is 0.14.4. You can install it from the context menu of the extension list view.
