### ISSUE TITLE
confusion occurs when there are multiple submodules

### ISSUE THREAD

**Issue by TQING1990** [bendera/vscode-commit-message-editor#28]
Hi
There are several sub-modules in my project. The first use is normal, but the commit message box cannot be filled in when it is used again. The message is filled in the commit message box of other sub-modules, which is the last one in the repository list. Only if I select other sub-modules first, and then switch back, it can be used normally.

**Comment by TQING1990** [comment]
vscode version: 1.53.2

**Comment by bendera** [comment]
Hi,

Is that project public? I would check it.

**Comment by TQING1990** [comment]
sorry, it is not public

**Comment by bendera** [comment]
From now the extension will display the selected repo name if there are multiple repos. I hope it resolves your problem.
