### ISSUE TITLE
open the commit message editor in win7 issues

### ISSUE THREAD

**Issue by zzwT1** [bendera/vscode-commit-message-editor#29]
There's nothing on it after open the commit message editor,How to solve it

**Comment by bendera** [comment]
Open the commit message editor tab and then open the command palette. Choose this command "Developer: Open Webview Developer Tools". Do you see any relevant error message in the dev console?
![command_palette](https://user-images.githubusercontent.com/3748508/109808493-79904980-7c27-11eb-91ab-2a4cf2ca445f.png)

**Comment by zzwT1** [comment]
thx，I found it was a vscode version problem(i was 1.47)，XD
