### ISSUE TITLE
Recent commits not displayed on code v1.42

### ISSUE THREAD

**Issue by storm1er** [bendera/vscode-commit-message-editor#3]
It was working fine on 1.41

![gnome-shell-screenshot-8IADF0](https://user-images.githubusercontent.com/9821946/74015991-fa800180-4991-11ea-80fa-faa8a77bca5a.png)

**Comment by bendera** [comment]
Thank you for your bug report. It seems to be a VSCode bug. Hopefully, it will be fixed in the next release.
https://github.com/microsoft/vscode/issues/90229

**Comment by bendera** [comment]
Fixed in 1.42.1
