### ISSUE TITLE
Text editor width stuck at minimum

### ISSUE THREAD

**Issue by GammaSigma1234** [bendera/vscode-commit-message-editor#38]
Please, see the attached picture to better understand what I mean.

What triggered the issue: I was working with my laptop PC, using an external monitor. Suddenly, I had to detach the laptop from the monitor, close the lid and physically walk to another position. When I opened the lid and returned to Visual Studio Code, I found that the text editing window was resized to a very tiny width, and I cannot figure out how to reset it to its former value. I tried reinstalling the extension, and the option in `settings.json` is `"commit-message-editor.view.fullWidth": true`.

Thank you in advance for your assistance. By the way, your extension is great!

![Problem](https://user-images.githubusercontent.com/74777624/128469469-e2ed9d24-1d15-4b44-a7dc-5975d26c92cc.png)

**Comment by datoux** [comment]
I have the same problem, but happened I think after updating VSCode today.

**Comment by GammaSigma1234** [comment]
I have another installation of VSC on another computer, and later I will check whether this problem appears there as well, after updating VSC to the latest version (I'm on my laptop now).

**Comment by bendera** [comment]
Hi,

Thank you for your bug report I could reproduce it. It will be fixed as soon as I can.

**Comment by GammaSigma1234** [comment]
I can confirm that the problem has disappeared after reloading the extension. Thank you very much!
