### ISSUE TITLE
VS Code does not launch an editor

### ISSUE THREAD

**Issue by rabayliss** [bendera/vscode-commit-message-editor#41]
Upon clicking on Open the Commit Message Editor, a window is opened in VS Code but shows no template and the window is not editable. (It is blank)
![image](https://user-images.githubusercontent.com/37907358/129786095-a112a1dd-dee0-44e2-b30d-0b2f6bd23ae4.png)

**Comment by bendera** [comment]
Hi,

Which VSCode version do you use?
When the commit message editor tab is the active tab, open the command palette (Ctrl+Shift+P) then choose the `Developer: Open Webview Developer Tools` command. Do you see any relevant errors in the webview dev console?

**Comment by rabayliss** [comment]
Hi,
Thanks for your help. I use this extension on another vs-code version and love it. So thanks for making it!!!
On this platform I am using
VSC: 1.43.0 on Windows_NT
![image](https://user-images.githubusercontent.com/37907358/129933139-b130736c-33a8-4886-82c3-85dd1169c8a2.png)

**Comment by bendera** [comment]
How could you install the extension? The specified vscode engine version in the extension is greater than your vscode version.

Anyway, I've fixed the bug and created a downgraded package that is compatible with your vscode version. 
[commit-message-editor-0.18.4-issue41.5.zip](https://github.com/bendera/vscode-commit-message-editor/files/7010254/commit-message-editor-0.18.4-issue41.5.zip)
The next version will contain the fix, so if you can install the latest version, feel free to install the next version as well.
