### ISSUE TITLE
[bug report] The selected repository cannot select

### ISSUE THREAD

**Issue by eallion** [bendera/vscode-commit-message-editor#44]
![屏幕截图 2021-09-15 124451](https://user-images.githubusercontent.com/1698841/133372178-432caee6-1bbe-4d87-9297-c475fc900adc.png)

This repo doesn't match the correct repo, `Selected repository` cannot select to change it. Unless reload VSCode. 
But after reload or restart, it will always display the repo used for the first time.

**Comment by bendera** [comment]
Hi,

That label just shows the repository that is currently selected, you cannot change the active repository with that. The built-in git extension doesn't provide any public method to change the current repository.

To select a repository click on the source control input box:

![image](https://user-images.githubusercontent.com/3748508/133389321-5794e9d4-b2e9-4bd3-910c-04a788886ce4.png)

or select it in the "source control repositories" section:

![image](https://user-images.githubusercontent.com/3748508/133389599-b04ed4f8-6d48-4cba-9c1b-da9c0df86dd2.png)

Did I understand your issue correctly? This is a frequently asked question, maybe I should make a small help button next to the label.

**Comment by eallion** [comment]
Hi there,
Thanks for your reply!

I know how to use it, even includes other conventional commits plugins.

In your case: 
When I want to commit a message to `vscode-commit-message-editor`, but the `Selected repository` is still `vscode-webview-elements`.

![11](https://user-images.githubusercontent.com/1698841/133546909-c64d53f2-d40f-4e1e-9faa-33b3ea28b15b.gif)

**Comment by bendera** [comment]
Okay, I could reproduce it. Thank you for the bug report.
