### ISSUE TITLE
Inscrutable behavior of repo selection

### ISSUE THREAD

**Issue by heartacker** [bendera/vscode-commit-message-editor#46]
as the git show
this extension can‘t select the right repo
![gce](https://user-images.githubusercontent.com/1876302/135218433-ffb0bd65-e871-4b5f-85be-2816ec6b13f6.gif)

**Comment by heartacker** [comment]
how to repro:
1. enable the Source Control Repositories
![image](https://user-images.githubusercontent.com/1876302/135219144-c0b45b25-4d4d-4981-b385-8dba57f594f2.png)
2. select one repo

**Comment by bendera** [comment]
Fixed in the latest version.
