### ISSUE TITLE
[Bug]Missing character when reopen "Edit commit message" window

### ISSUE THREAD

**Issue by RobertIndie** [bendera/vscode-commit-message-editor#5]
for example:
normal situation:
![image](https://user-images.githubusercontent.com/16974619/80866401-09403100-8cc1-11ea-8783-93183ce5b79f.png)

But when I committed message or change to other file window and back, the last character of some fields will be missing.
![image](https://user-images.githubusercontent.com/16974619/80866456-545a4400-8cc1-11ea-87ef-463d2405120d.png)

**Comment by bendera** [comment]
Ouch, that's a bug. Good catch!

**Comment by bendera** [comment]
Fixed.
