### ISSUE TITLE
Support for newline in Prefix and  Suffix

### ISSUE THREAD

**Issue by LuWa-at-work** [bendera/vscode-commit-message-editor#52]
Currently if "test \n" is set as newline, the \n is escaped to \\n and is written as "\n" to the commitmessage.

As Workaround you could change the Prefix/ Suffix in the exported File and then reimport it...

But it would be much nicer if this could be done direktly in the Settingspage. Maybe as simple as allowing multiline inputs for Pre-/Suffix...

**Comment by bendera** [comment]
I've added to my TODO list.
