### ISSUE TITLE
Incorrect behavior when selecting active repository

### ISSUE THREAD

**Issue by thexdd** [bendera/vscode-commit-message-editor#54]
We are using a submodule in our repository.

<img width="1225" alt="Screen Shot 2022-05-10 at 12 05 12" src="https://user-images.githubusercontent.com/13180647/167592512-a3101947-1bee-4433-9752-0e3d0a9d6b59.png">

Sometimes when I click on the "message" field in the source control window, the "selected repository" field shows the wrong repository being selected. This often happens when I collapse the repository item in the source control window. The behavior usually gets broken at this moment.

**Comment by bendera** [comment]
The factory git API is used in the extension and that API doesn't allow selecting the active repository. So the extension only shows the selected repo. It will be more clear if you enable the "Source Control Repositories" view:
![source-control-repositories-view](https://user-images.githubusercontent.com/3748508/167954451-59a2fc2e-0f22-492e-9f54-a062ad8908b9.png)
After that, it will be straightforward what the active repo is:
![selected-repo](https://user-images.githubusercontent.com/3748508/167955288-93688993-17ac-4483-b7b5-9f031adefcbc.png)
You can select multiple repositories simultaneously, in this case, you can select the active repo by clicking in the text field.
![multiple-selected](https://user-images.githubusercontent.com/3748508/167955666-34733053-912f-4713-be82-97be5366237b.png)

**Comment by bendera** [comment]
FYI, Hopefully, I fixed this issue in the latest version.
