### ISSUE TITLE
Wrong repository selected with multiple projects in workspace

### ISSUE THREAD

**Issue by piarullir** [bendera/vscode-commit-message-editor#57]
In a workspace with multiple folders (projects) attached there is an "Open commit message editor" pencil on each project,
but for any pencil key i press the same thing happens:

the "Edit commit message" tab opens and it shows always the last project repository in "Selected repository" (and i cannot change it)

**Comment by bendera** [comment]
It is the same issue as this:
https://github.com/bendera/vscode-commit-message-editor/issues/54
I should figure out something for this.

**Comment by bendera** [comment]
Fixed.
