### ISSUE TITLE
[Bug]Save message to wrong place when repo has submodule

### ISSUE THREAD

**Issue by RobertIndie** [bendera/vscode-commit-message-editor#6]
1. In main repo, click the "Open the commit message editor" button
![image](https://user-images.githubusercontent.com/16974619/81195874-f6936800-8ff0-11ea-8676-46ed987a8932.png)
2. But when I save the commit message, it saved to the submodule's git(wrong place).
![image](https://user-images.githubusercontent.com/16974619/81196087-2e021480-8ff1-11ea-9973-84f94cf8fe5d.png)

**Comment by bendera** [comment]
As I see it, that is not a bug. Click on an item in the "Source control provider" view and only one repository will be visible. If multiple items are selected, the last one will be the active repo.
