### ISSUE TITLE
.vscodeignore should exclude CHANGELOG file

### ISSUE THREAD

**Issue by tjx666** [bendera/vscode-commit-message-editor#60]
<img width="958" alt="image" src="https://user-images.githubusercontent.com/41773861/177050362-33280265-9a2a-4764-b557-dd6f4786921c.png">

<img width="959" alt="image" src="https://user-images.githubusercontent.com/41773861/177050375-140011fb-e736-47bd-a06e-285928f55780.png">

**Comment by bendera** [comment]
Thanks, I'm going to fix it in the next release.
