### ISSUE TITLE
Selected repository does not automatically update

### ISSUE THREAD

**Issue by joxtoyod** [bendera/vscode-commit-message-editor#70]
When you have multiple repo in your workspace, the "selected repository" doesn't pick up the correct repo

**Comment by clement-deltel** [comment]
I currently have the same issue as you. It always grabs the last repository from the list, alphabetically ordered.

**Comment by bendera** [comment]
The "selected repository" is only an indicator, not an interactive selector. I describe the reasons here:
https://github.com/bendera/vscode-commit-message-editor/issues/54#issuecomment-1124340758

Since then I have found a possible solution, although I haven't tried it yet.

**Comment by bendera** [comment]
Fixed. And I found a solution to select a repository from the editor tab in a multi-root workspace. I will implement in the next version.
