### ISSUE TITLE
Too many empty lines

### ISSUE THREAD

**Issue by gtianw** [bendera/vscode-commit-message-editor#77]
**setting**
```json
    "commit-message-editor.dynamicTemplate": [
        "{type}{scope}: {subject}",
        "",
        "{body}",
        "",
        "{breaking_change}",
        "",
        "{issue}"
    ]
```

**version**
0.20.0

**Problem Description**
if `body`, `breaking_change`, `issue` are all empty, the commit message will generate 5 trailing empty lines.

**Comment by bendera** [comment]
fixed in the latest version
