### ISSUE TITLE
Options not applied to Form

### ISSUE THREAD

**Issue by l0ner** [bendera/vscode-commit-message-editor#78]
Hi

The options "commit-message-editor.view.useMonospaceEditor" and "commit-message-editor.view.rulers" are not applied to the fileds in the form view.

**Comment by bendera** [comment]
Hi

These options belong to the text view.

**Comment by l0ner** [comment]
OK, great. How to apply these to the form view? Is the form view configurable in any way when it comes to having guides/limiting max line length and changing the font?

**Comment by bendera** [comment]
There is a maxLenght option for the textfields, see: https://github.com/bendera/vscode-commit-message-editor#tokens

The monospace editor cannot be used in the form view currently but would make sense. I will consider this idea.

**Comment by l0ner** [comment]
the maxLenght, when applied to the fields limit the total character count, which is fine for scope and short description, but not for body.

What i want to do is not have any limits when it comes to total character count for body, but have a limit for the length of a single line in the Body field (or a ruler, having visual indicator whould be fine, but that would require the body field to use monospace font)

Same goes for the footer, where having an additional limit for how may lines the footer can be would be nice too.

**Comment by l0ner** [comment]
Great to hear about "monospace editor"! 

Having a functionality that automatically makes the commit message generated from the form to adhere to the max line lenght would be great too. It's essentially what blocks my team from using this plugin.

**Comment by bendera** [comment]
Added in v0.23.0
