### ISSUE TITLE
The value of a token of type `boolean` has no text input in the commit form editor view

### ISSUE THREAD

**Issue by ctison** [bendera/vscode-commit-message-editor#79]
### From the default configuration exported as JSON

![image](https://user-images.githubusercontent.com/17789536/218277381-1f608603-077f-452e-9023-4aff4f4529f2.png)

### From the commit form editor view

![image](https://user-images.githubusercontent.com/17789536/218277343-e88b5807-3052-48b7-9c98-2084d5d86359.png)

**Comment by bendera** [comment]
Thanks for the bug report!
