### ISSUE TITLE
Support to use Code Spell Checker for commit messages

### ISSUE THREAD

**Issue by umarhussain15** [bendera/vscode-commit-message-editor#9]
Hi, 
Thanks for this nice extension, I use it regularly in my workflow.

I have a suggestion to add the ability to use extensions like [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) within the text editor for commit message.
I don't know if VSCode directly supports this or not, but if there is a way to somehow add some kind of spell check that will be great.

There is an open issue on VSCode regarding this not sure when that will be resolved: https://github.com/Microsoft/vscode/issues/35571

Thanks.

**Comment by bendera** [comment]
Hi Umar,

Thank you for your feedback, I'm glad you find my extension useful.

Spell checking would be a great improvement, but currently, I don't know how to implement it. As far as I know, there is no built-in spell checker in the VSCode. As I see, the Code Spell Checker couldn't help me. Maybe I could use a command-line tool like [aspell](http://aspell.net/). I'm looking for a solution.

**Comment by ctsstc** [comment]
It drives me nuts that I get spell checking across VSCode except for the built-in commit messages. I was hoping this extension would handle that.

**Comment by ssbarnea** [comment]
Any chance to get this addressed? The whole point of having a full editor window for commit message is to ease writing good messages, like respecting 50/72 rule, avoid spellchecking errors and following another project specific requirements.

**Comment by DervishD** [comment]
From what I've read about this looks like you can tell `VSCode` that the text area you are using in your extension has a language ID of `scminput`. That would enable, at least, `cSpell`.

I have not read the relevant code so I don't know if this is possible or not. I know that is how it is done in `VSCode` itself, in the small textarea for commit messages.

No big deal anyway, since when I click the `Save` button and the text is copied to that area, is spell checked anyway, but it would be great to see that checking happen when writing the message!

Thanks for the extension, BTW.

**Comment by bendera** [comment]
Hi,

This extension uses the Webview API and in the Webview API, the "native" VSCode widgets like the Monaco Editor, Tree View, Source Control Inputbox, etc. can't be accessed. Although the extension's textarea looks like a "native" VSCode element, it's just a nicely decorated plain textarea. What I could do is include the cSpell library. However, on the one hand, it's bigger than the whole extension, on the other hand, it would need a huge effort to implement a similar user experience like the native API. I will never have enough free time to implement this.

**Comment by umarhussain15** [comment]
Since the VSCode has [added the spell check support](https://github.com/microsoft/vscode/issues/35571) in the built-in commit message text area, I will close this issue. 
As @bendera mentioned, adding the spell check to the extension will be a large effort, so as a fallback the spelling can be checked in the built-in commit message text area

**Comment by DervishD** [comment]
@umarhussain15 and @bendera I completely understand. I thought it could be as easy as to mark the textarea so the CSpell extension automagically processed the contents, but frankly it does not make any sense to write a ton of code or, even worse, including the full CSpell extension with this one, for something very easy to achieve by just clicking the `Save` button and checking the spelling results in the built-in commit message area.

Thanks you both for your attention and for replying and explaining everything to me 😄
