### ISSUE TITLE
not work for the first commit

### ISSUE THREAD

**Issue by shinyypig** [bendera/vscode-commit-message-editor#94]
<img width="1725" alt="image" src="https://user-images.githubusercontent.com/30233673/235728075-2aef7b99-db56-42d4-b87a-fe4eadf5825f.png">

I have disabled all other extensions.

**Comment by bendera** [comment]
I also experience this sometimes. Please let me know if you figured out how to be reproduced.

**Comment by bendera** [comment]
I published a pre-release version on the VSCode Marketplace. Its version number is 0.24.1683149829
I'm not sure if this fixes the bug, but it is a possible solution to fix a bug that can cause this phenomenon.

**Comment by shinyypig** [comment]
fixed in #96

**Comment by shinyypig** [comment]
> I published a pre-release version on the VSCode Marketplace. Its version number is 0.24.1683149829
> I'm not sure if this fixes the bug, but it is a possible solution to fix a bug that can cause this phenomenon.

I have tried this pre-release version, still not work.

**Comment by gtianw** [comment]
> I also experience this sometimes. Please let me know if you figured out how to be reproduced.

@bendera 
I have also encountered this issue occasionally, even if it's not the first commit.
I couldn't find any patterns. However, I can confirm that it was introduced by v0.24.1.
After I downgraded to 0.24.0, everything worked fine.
